## Getting hands-on with NumPy

This assignment aims at acquainting you with numpy methods which you will require during this project. So, it is advised that you follow the instructions before each code cell diligently.<br>
You are encouraged to google (or ChatGPT) things up wherever you feel stuck : )<br>
But make sure you understand things and not just copy-paste them

### **Import the NumPy library**

In [1]:
import numpy as np

### **Initialising arrays in NumPy**

NumPy offers several way to initialise arrays
* Create a $2\times3$ array identical to
$\begin{bmatrix}
1 & 2 & 4\\
7 & 13 & 21\\
\end{bmatrix}$ and a $2\times2\times3$ array identical to
$\begin{bmatrix}
[1 & 2 & 3] & [4 & 5 & 6]\\
[7 & 8 & 9] & [10 & 11 & 12]\\
\end{bmatrix}$

In [ ]:
# START
    # Enter the values for the 2x3 array
arr1 = np.array([[None, None, None], [None, None, None]])
    # Similarly initialise the second array and assign it to arr2
arr2 = np.array(None)
# END

print("arr1:\n", arr1)
print("Shape of arr1:", arr1.shape, "; No. of Dimensions:", arr1.ndim)
print("arr2:\n", arr2)
print("Shape of arr2:", arr2.shape, "; No. of Dimensions:", arr2.ndim)

Note that the shapes and no. of dimensions of the arrays have been printed. These attributes help a lot in debugging

Now create
* A $2\times3$ array **arr3** of all zeros using **np.zeros**
* A $2\times3$ array **arr4** of all ones using **np.ones**
* A $2\times3$ array **arr5** of all fives using **np.full**
* A 1-D array **arr6** containing only even numbers in the range $0-20$ using **np.arange**
* Repeat last task using **np.linspace** and name it **arr7**

In [ ]:
# START
arr3 = None
arr4 = None
arr5 = None
arr6 = None
arr7 = None
# END

print(f"arr3: {arr3}")
print(f"arr4: {arr4}")
print(f"arr5: {arr5}")
print(f"arr6: {arr6}")
print(f"arr7: {arr7}")

Creating arrays with random values
* Create a $2\times3$ array **arr8** using **np.random.rand**
* Create a $2\times3$ array **arr9** with rnadom integer values in $[5,8)$ using **randint** method of **random** module

In [ ]:
# START
arr8 = None
arr9 = None
# END

print(arr8)
print(arr9)

### **Accessing arrays in NumPy**

Initialise an array **arr** $=
\begin{bmatrix}
1 & 3 & 5 & 7\\
9 & 11 & 13 & 15\\
17 & 19 & 21 & 23
\end{bmatrix}$ and perform the following operations:<br>

* Extract and print the element 13 using numpy array indexing
* Use array slicing to print only the 2nd and 4th columns of only the 2nd and 3rd rows of *arr*
* Print all the values in *arr* which are a multiple of 3

In [17]:
import numpy as np
arr = np.array([[1,3,5,7],[9,11,13,15],[17,19,21,23]])
print(arr)
print(arr[1,2])



multiples_of_3 = arr[arr % 3 == 0]
print(multiples_of_3)

print()

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
13
[ 3  9 15 21]



### **Reshaping and Broadcasting**

* Reshape *arr* into a $2\times6$ matrix and print it
* Print the transpose of *arr*

In [18]:
reshaped_arr = arr.reshape(2, 6)
print(reshaped_arr)

print(arr.transpose)

[[ 1  3  5  7  9 11]
 [13 15 17 19 21 23]]
<built-in method transpose of numpy.ndarray object at 0x120385770>


Moving on to broadcasting, you are given two arrays **a** $=
\begin{bmatrix}
1 & 2 & 3
\end{bmatrix}$ and **b** $=
\begin{bmatrix}
4\\
5
\end{bmatrix}$<br>

Try adding these two arrays using **+** operator and print the result

In [2]:
a = np.array([1,2,3])
b = np.array([4,5]).reshape(2,1)
c = a+b
print(c)

[[5 6 7]
 [6 7 8]]


You will find that NumPy repeats the values for the arrays to match dimensions and be compatible while doing a particular matrix operation. In general, a dimension is compatible if it is equal to the respective dimension of the other array or if it is 1

### **Miscellaneous**

Be cautious while multiplying matrices and don't confuse the functions doing element wise multiplication with the ones doing traditional matrix multipication.

In [9]:
a = np.array([1,2,3])

In [12]:
# Use np.multiply and the * operator to multiply 'arr' and 'a' in this cell, note that you may need to take transpose of one or the other matrix during this operation

arr_t = arr.T

result_with_operator = arr_t * a
result_with_multiply = np.multiply(arr_t, a)

print(result_with_operator)
print(result_with_multiply)


[[ 1 14 39]
 [ 3 18 45]
 [ 5 22 51]]
[[ 1 14 39]
 [ 3 18 45]
 [ 5 22 51]]


In [10]:
# Use np.matmul and np.dot functions to multiply 'arr' and 'a' in this cell, again you may need to take transpose of one or the other matrix

result_with_matmul = np.matmul(arr, a)
result_with_dot = np.dot(arr, a)

print(result_with_matmul)
print(result_with_dot)


[22 58 94]
[22 58 94]
